### ISSUE TITLE
Implementar la barra de navegación

### ISSUE THREAD

**Issue by Jhonproyec** [Jhonproyec/proyectoFinal#1]

**Comment by Birdy901** [comment]
A la página de inicio (home) agregué la Navbar con los distintos controles: Control de médicos, de pacientes, especialidades, consultas y laboratorios. Solo los controles que tienen su componente se les agregó el enrutamiento. 
Había tenido un pequeño problema, que cloné el proyecto antes de los cambios de mi compañero Cámbara y cuando utilicé el comando "git pull" no actualizaban sus cambios, así que tuve que volver a clonarlo después de sus cambios y así poder comenzar a editar.

**Comment by Jhonproyec** [comment]
Limpieza en el archivo html del componente home.

en el archivo html del componente home únicamente debe estar la etiqueta nav y todo lo que está dentro de ella, las demas etiquetas como html, body, head, title, script, etc deben eliminarse, ya que bootstrap está instalado en la aplicación de angular, no es necesario volver a hacer referencia a sus estilos

**Comment by Birdy901** [comment]
Realicé la limpieza en el archivo html del componente home, aún queda pendiente el sistema que simule un inicio de sesión
