### ISSUE TITLE
Control de pacientes

### ISSUE THREAD

**Issue by Jhonproyec** [Jhonproyec/proyectoFinal#3]
Implementar la vista de control de pacientes y la lógica de CRUD

**Comment by Birdy901** [comment]
Agregué la vista en el archivo HTML del componente pacientes, tuve algunos problemas con el título de tabla porque se movía abajo del thead, pero lo pude solucionar colocando el h2 del título afuera de la tabla. También tuve algunos inconvenientes cambiando el tamaño de los contenedores y agregándole color a las tablas, pero averiguaré sobre eso más adelante
