### ISSUE TITLE
Control de Consultas

### ISSUE THREAD

**Issue by Jhonproyec** [Jhonproyec/proyectoFinal#4]
Implementar la vista de control de consultas y la lógica de CRUD

**Comment by Jhonproyec** [comment]
En el input para agregar la fecha, en html no se pueden asignar dos tipos a un input, para agregar la fecha puede usar el tipo date en el input, ya que  esto le puede dar problemas al tratar de llamar los valores desde el archito typescript

**Comment by RebeckaXL** [comment]
El día de hoy realice nuevamente el código para darle una mejor vista 
![image](https://user-images.githubusercontent.com/92342049/138803469-1ccda199-55d3-4e54-a8f4-e8cd82ac1738.png)
espero se pueda revisar, post a esto realizare las opciones para los médicos, especialidades y pacientes. 
espero sus revisiones.

**Comment by Jhonproyec** [comment]
para realizar el crud de consultas, tuvimos que guardar la información en el localstorage, ya que el backend nos daba un error, lo reportamos pero no ubo respuesta
